# Generated by Django 5.2.4 on 2025-07-28 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Простая заявка',
                'verbose_name_plural': 'Простые заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SingleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'complex',
                'verbose_name_plural': 'complexs',
            },
        ),
        migrations.CreateModel(
            name='SingleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='single_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Одиночное изображение',
                'verbose_name_plural': 'Одиночные изображения',
            },
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('text_ru', models.TextField(max_length=500, null=True, verbose_name='Текст')),
                ('text_ky', models.TextField(max_length=500, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текстовое сообщение',
                'verbose_name_plural': 'Текстовые сообщения',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('area', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Площадь (м²)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('deal_type', models.CharField(max_length=50, verbose_name='Тип сделки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('property_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип недвижимости')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Площадь участка (сотки)')),
                ('commercial_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип коммерции')),
                ('condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Состояние')),
                ('utilities', models.TextField(blank=True, null=True, verbose_name='Коммуникации')),
                ('purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назначение')),
                ('parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Документ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='applications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'verbose_name': 'Заявка с объявлением',
                'verbose_name_plural': 'Заявки с объявлениями',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/', verbose_name='Изображение')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Фото квартиры',
                'verbose_name_plural': 'Фотографии квартиры',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'unique_together': {('city', 'district')},
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.location', verbose_name='Локация (город/район)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='single_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.singlefield', verbose_name='complex'),
        ),
    ]
