# Generated by Django 5.2.4 on 2025-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_textmessage_text_ky_textmessage_text_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='series',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия'),
        ),
    ]
