# Generated by Django 5.2.4 on 2025-07-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_application_user_listinglike_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='listing',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.DeleteModel(
            name='ListingLike',
        ),
    ]
