# Generated by Django 5.2.4 on 2025-07-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_application_listing_remove_application_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='single_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Одиночное изображение',
                'verbose_name_plural': 'Одиночные изображения',
            },
        ),
    ]
