# Generated by Django 5.2.4 on 2025-07-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_singleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.singleimage', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='application',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing', verbose_name='Объявление'),
        ),
    ]
