# Generated by Django 5.2.4 on 2025-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_application_image_application_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текстовое сообщение',
                'verbose_name_plural': 'Текстовые сообщения',
            },
        ),
    ]
