# Generated by Django 5.2.4 on 2025-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_textmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listing_videos/', verbose_name='Видео'),
        ),
    ]
