# Generated by Django 5.2.4 on 2025-07-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_application_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
