# Generated by Django 5.2.4 on 2025-07-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_application_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
    ]
