# Generated by Django 5.2.4 on 2025-07-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_application_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='image',
        ),
        migrations.RemoveField(
            model_name='application',
            name='listing',
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
