# Generated by Django 5.2.4 on 2025-07-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_application_image_application_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Простая заявка',
                'verbose_name_plural': 'Простые заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка с объявлением', 'verbose_name_plural': 'Заявки с объявлениями'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.listing', verbose_name='Объявление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
