# Generated by Django 5.2.4 on 2025-07-25 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_simpleapplication_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contact_phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
