# Generated by Django 5.2.4 on 2025-07-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_application_contact_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleApplication',
            new_name='Bit',
        ),
    ]
