# Generated by Django 5.2.4 on 2025-07-26 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_rename_simpleapplication_bit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='video',
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='listing_media/', verbose_name='Файл')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, verbose_name='Тип')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='listings.listing', verbose_name='Объявление')),
            ],
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
