# Generated by Django 5.2.4 on 2025-07-26 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_remove_listing_video_listingmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listing_videos/', verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/', verbose_name='Изображение')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Фото квартиры',
                'verbose_name_plural': 'Фотографии квартиры',
            },
        ),
        migrations.DeleteModel(
            name='ListingMedia',
        ),
    ]
