# Generated by Django 5.2.4 on 2025-07-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_video_listingimage_delete_listingmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='commercial_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип коммерции'),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='listing',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Площадь участка (сотки)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Наличие парковки'),
        ),
        migrations.AddField(
            model_name='listing',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='listing',
            name='utilities',
            field=models.TextField(blank=True, null=True, verbose_name='Коммуникации'),
        ),
    ]
