# Generated by Django 5.2.4 on 2025-07-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_listing_commercial_type_listing_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('land', 'Земля'), ('commercial', 'Коммерческая'), ('other', 'Другое')], default='apartment', max_length=20, verbose_name='Тип недвижимости'),
        ),
    ]
