# Generated by Django 5.2.4 on 2025-07-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listing_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='video',
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назначение'),
        ),
    ]
