# Generated by Django 5.2.4 on 2025-07-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_remove_listing_video_alter_listing_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=50, verbose_name='Тип сделки'),
        ),
    ]
