# Generated by Django 5.2.4 on 2025-07-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_listing_document_alter_listing_deal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Одно поле',
                'verbose_name_plural': 'Одно поле',
            },
        ),
    ]
