# Generated by Django 5.2.4 on 2025-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_singlefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefield',
            name='value',
        ),
        migrations.AddField(
            model_name='singlefield',
            name='text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Документ'),
        ),
    ]
