# Generated by Django 5.2.4 on 2025-07-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_remove_singlefield_value_singlefield_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlefield',
            old_name='text',
            new_name='value',
        ),
    ]
