# Generated by Django 5.2.4 on 2025-07-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_rename_text_singlefield_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='deal_type',
            field=models.CharField(max_length=50, verbose_name='Тип сделки'),
        ),
    ]
