# Generated by Django 5.2.4 on 2025-07-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_listing_deal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='single_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.singlefield', verbose_name='Одно поле'),
        ),
    ]
