# Generated by Django 5.2.4 on 2025-07-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_listing_single_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='single_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.singlefield', verbose_name='complex'),
        ),
    ]
