# Generated by Django 5.2.4 on 2025-07-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_listing_single_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlefield',
            options={'verbose_name': 'complex', 'verbose_name_plural': 'complexs'},
        ),
    ]
