# Generated by Django 5.2.4 on 2025-07-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_alter_singlefield_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='text_ky',
            field=models.TextField(max_length=500, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='text_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Текст'),
        ),
    ]
